force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>A physical or electronic copy of a written work created by a author or set of authors.</description>
    <label>Book</label>
    <nameField>
        <label>Book</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderBook__c/OrderBook__c.object-meta.xml
<CustomObject>
    <description>Junction object</description>
    <label>OrderBook</label>
    <nameField>
        <label>OrderBook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderBooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderBook__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>OrderBooks</relationshipLabel>
    <relationshipName>OrderBooks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderBook__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>OrderBooks</relationshipLabel>
    <relationshipName>OrderBooks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OrderTriggerHandler.cls
public class OrderTriggerHandler {
     public static void HandleBeforeInsert(Set<Order> currOrders) {
        List<OrderBook__c> books = [SELECT BookId__c, order__c FROM OrderBook__c];
        Set<Id> bookIds = new Set<Id>();
        Map<Id, Decimal> idToBook = new Map<Id, Integer>();
        Map<Id, Integer> idToOrder = new Map<Id, Integer>();
        Set<Id> orderIds = new Set<Id>();

        for (OrderBook__c  i : books ) {
            bookIds.add(i.bookId__c);
            orderIds.add(i.order__c);
        }
        
        List<Book__c> currentBooks = [SELECT Id, Price__c FROM Book__c WHERE Id IN :bookIds];

        for(Book__c i : currentBooks) {
            idToBook.put(i.Id, i.Price__c);
        }

        List<Order> myOrders = [SELECT Id, Name FROM Order WHERE Id NOT IN :orderIds];
        
        currOrders.removeAll(myOrders);
        for (Order i : currOrders) {
            if(i.Final_Cost__c == null) {
                for(OrderBook__c j : books) {
                        i.Final_Cost__c = idToBook.get(j.bookId__c);
                } 
            }
        }
    }
}